export const BLOG_POSTS = [
    {
        id: 1,
        title: "The Future of AI in 2025",
        excerpt: "Exploring the emerging trends in Artificial Intelligence and how they will shape our daily lives and industries.",
        date: "Jan 03, 2025",
        author: "Alex Smith",
        category: "Artificial Intelligence",
        image: "bg-gradient-to-br from-primary to-slate-900",
        readTime: "5 min read",
    },
    {
        id: 2,
        title: "Getting Started with Next.js 15",
        excerpt: "A comprehensive guide to building your first full-stack application with the latest features of Next.js.",
        date: "Dec 28, 2024",
        author: "Mike Chen",
        category: "Web Development",
        image: "bg-gradient-to-br from-secondary to-slate-900",
        readTime: "8 min read",
    },
    {
        id: 3,
        title: "Cybersecurity Best Practices for Students",
        excerpt: "Essential tips and tools to keep your digital identity safe while browsing and working online.",
        date: "Dec 15, 2024",
        author: "Sarah Jones",
        category: "Security",
        image: "bg-gradient-to-br from-accent to-slate-900",
        readTime: "6 min read",
    },
    {
        id: 4,
        title: "Mastering Data Structures: Trees",
        excerpt: "Deep dive into tree data structures, traversal algorithms, and real-world applications in software engineering.",
        date: "Nov 30, 2024",
        author: "James Wilson",
        category: "Algorithms",
        image: "bg-gradient-to-br from-primary to-slate-900",
        readTime: "10 min read",
    },
    {
        id: 5,
        title: "UI/UX Design Principles for Developers",
        excerpt: "Learn the fundamental principles of design to create user-friendly and visually appealing interfaces.",
        date: "Nov 20, 2024",
        author: "Emily Davis",
        category: "Design",
        image: "bg-gradient-to-br from-secondary to-slate-900",
        readTime: "7 min read",
    },
    {
        id: 6,
        title: "Introduction to Cloud Computing",
        excerpt: "Understanding the basics of cloud services, deployment models, and how to choose the right provider.",
        date: "Nov 10, 2024",
        author: "Daniel Brown",
        category: "Cloud",
        image: "bg-gradient-to-br from-accent to-slate-900",
        readTime: "6 min read",
    }
];
